CREATE SCHEMA IF NOT EXISTS BE;

CREATE TABLE IF NOT EXISTS BE.BE_CONTROL_SUPERVIVENCIA (
                                                               COD_EMPRESA         varchar(255),
    NUP                 varchar(255),
    COD_PER_FISICA      varchar(255),
    CORRELATIVO         numeric(10,0),
    FECHA1              date,
    FECHA2              date,
    ESTADO              varchar(255),
    COD_CAUSAL          numeric(3,0),
    FORMULARIO          numeric(10,0),
    TIPO_DOCUMENTO      varchar(255),
    NUM_DOCUMENTO       varchar(255),
    FECHA_ADICION       date,
    ADICIONADO_POR      varchar(255),
    FECHA_MODIFICACION  date,
    MODIFICADO_POR      varchar(255),
    NUMERO_SUSPENSION   numeric(10,0),
    NUM_PLA             numeric(8,0),
    TIPO_PLA            numeric(3,0),
    FECHA_ENTREGA       date,
    FECHA_ENVIO         date,
    CONTROL_CALIDAD     date,
    FECHA_ESCANEADO     date,
    USUARIO_QC          varchar(255),
    USUARIO_ENTREGA     varchar(255),
    USUARIO_ENVIO       varchar(255),
    USUARIO_ESCANEA     varchar(255),
    COD_HUELLA          numeric(10,0),
    CANAL_CONTROL       varchar(255),

    CONSTRAINT PK_CONTROL_SUPERV
    PRIMARY KEY (COD_EMPRESA, NUP, COD_PER_FISICA, CORRELATIVO, COD_CAUSAL)
    );

SELECT schemaname, tablename
FROM pg_tables
WHERE tablename ILIKE 'be_control_supervivencia';

INSERT INTO BE.BE_CONTROL_SUPERVIVENCIA (
    COD_EMPRESA,NUP,COD_PER_FISICA,CORRELATIVO,FECHA1,FECHA2,ESTADO,COD_CAUSAL,
    FORMULARIO,TIPO_DOCUMENTO,NUM_DOCUMENTO,FECHA_ADICION,ADICIONADO_POR,
    FECHA_MODIFICACION,MODIFICADO_POR,NUMERO_SUSPENSION,NUM_PLA,TIPO_PLA,
    FECHA_ENTREGA,FECHA_ENVIO,CONTROL_CALIDAD,FECHA_ESCANEADO,
    USUARIO_QC,USUARIO_ENTREGA,USUARIO_ENVIO,USUARIO_ESCANEA,COD_HUELLA,CANAL_CONTROL
) VALUES (
             '01','NUP0001','PF0001',1,'2026-02-01','2026-02-10','ACTIVO',101,
             1000000001,'DUI','01234567-8','2026-02-01','DANIEL',
             '2026-02-02','DANIEL',10,12345678,1,
             '2026-02-03','2026-02-04','2026-02-05','2026-02-06',
             'QC_USER1','ENT_USER1','ENV_USER1','ESC_USER1',5001,'WEB'
         );

INSERT INTO BE.BE_CONTROL_SUPERVIVENCIA (
    COD_EMPRESA,NUP,COD_PER_FISICA,CORRELATIVO,FECHA1,FECHA2,ESTADO,COD_CAUSAL,
    FORMULARIO,TIPO_DOCUMENTO,NUM_DOCUMENTO,FECHA_ADICION,ADICIONADO_POR,
    FECHA_MODIFICACION,MODIFICADO_POR,NUMERO_SUSPENSION,NUM_PLA,TIPO_PLA,
    FECHA_ENTREGA,FECHA_ENVIO,CONTROL_CALIDAD,FECHA_ESCANEADO,
    USUARIO_QC,USUARIO_ENTREGA,USUARIO_ENVIO,USUARIO_ESCANEA,COD_HUELLA,CANAL_CONTROL
) VALUES (
             '01','NUP0002','PF0002',1,'2026-02-05',NULL,'PENDIENTE',102,
             1000000002,'PAS','A1234567','2026-02-05','SYSTEM',
             NULL,NULL,NULL,87654321,2,
             NULL,NULL,NULL,NULL,
             NULL,NULL,'ENV_USER2',NULL,5002,'SUCURSAL'
         );

INSERT INTO BE.BE_CONTROL_SUPERVIVENCIA (
    COD_EMPRESA,NUP,COD_PER_FISICA,CORRELATIVO,FECHA1,FECHA2,ESTADO,COD_CAUSAL,
    FORMULARIO,TIPO_DOCUMENTO,NUM_DOCUMENTO,FECHA_ADICION,ADICIONADO_POR,
    FECHA_MODIFICACION,MODIFICADO_POR,NUMERO_SUSPENSION,NUM_PLA,TIPO_PLA,
    FECHA_ENTREGA,FECHA_ENVIO,CONTROL_CALIDAD,FECHA_ESCANEADO,
    USUARIO_QC,USUARIO_ENTREGA,USUARIO_ENVIO,USUARIO_ESCANEA,COD_HUELLA,CANAL_CONTROL
) VALUES (
             '02','NUP0001','PF0001',2,'2026-01-20','2026-01-25','CERRADO',103,
             1000000010,'NIT','0614-200196-101-1','2026-01-20','ADMIN',
             '2026-01-26','ADMIN',20,11223344,3,
             '2026-01-21','2026-01-22','2026-01-23','2026-01-24',
             'QC_USER3','ENT_USER3','ENV_USER3','ESC_USER3',6001,'APP'
         );


ALTER TABLE be.be_control_supervivencia
    ALTER COLUMN cod_causal TYPE integer USING cod_causal::integer;

ALTER TABLE be.be_control_supervivencia
    ALTER COLUMN correlativo TYPE integer USING correlativo::integer;

ALTER TABLE be.be_control_supervivencia
    ALTER COLUMN formulario TYPE integer USING formulario::integer;

ALTER TABLE be.be_control_supervivencia
    ALTER COLUMN numero_suspension TYPE integer USING numero_suspension::integer;

ALTER TABLE be.be_control_supervivencia
    ALTER COLUMN num_pla TYPE integer USING num_pla::integer;

ALTER TABLE be.be_control_supervivencia
    ALTER COLUMN tipo_pla TYPE integer USING tipo_pla::integer;

ALTER TABLE be.be_control_supervivencia
    ALTER COLUMN cod_huella TYPE integer USING cod_huella::integer;